### ISSUE TITLE
Dimension out of range for Softmax in dialog_model.py  

### ISSUE THREAD

**Issue by shivamswarnkar** [facebookresearch/end-to-end-negotiator#16]
I am getting this error when I try to run reinforce.py. 
`Traceback (most recent call last):
  File "reinforce.py", line 164, in <module>
    main()
  File "reinforce.py", line 158, in main
    reinforce.run()
  File "reinforce.py", line 57, in run
    self.dialog.run(ctxs, self.logger)
  File "/home/ss8464/dl/nego_comm/main/src/dialog.py", line 170, in run
    out = writer.write()
  File "/home/ss8464/dl/nego_comm/main/src/agent.py", line 128, in write
    100, self.args.temperature)
  File "/home/ss8464/dl/nego_comm/main/src/models/dialog_model.py", line 300, in write
    prob = F.softmax(scores)
  File "/share/apps/pytorch/20171124/python3.6/gnu/lib/python3.6/site-packages/torch/nn/functional.py", line 818, in softmax
    return torch._C._nn.softmax(input, dim)
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)`

**Comment by denisyarats** [comment]
Hi, could you please share the arguments?
