### ISSUE TITLE
Invalid argument 2: dimension 2 out of range of 2D tensor

### ISSUE THREAD

**Issue by diegosoaresub** [facebookresearch/end-to-end-negotiator#8]
Hello, 

When the code below is run a error is throwed. Could someone help me with this problem?

ps: cuda support is disabled.

`# concatenate attention and context hidden and pass it to the selection encoder`
`h = torch.cat([attn, ctx_h], 2).squeeze(0)`
`h = self.dropout(h)`
`h = self.sel_encoder.forward(h)`

python train.py data data/negotiate
--bsz 16
--clip 0.5 \
--decay_every 1 \
--decay_rate 5.0 \
--dropout 0.5 \
--init_range 0.1 \
--lr 1 \
--max_epoch 30 \
--min_lr 0.01 \
--momentum 0.1 \
--nembed_ctx 64 \
--nembed_word 256 \
--nesterov \
--nhid_attn 256 \
--nhid_ctx 64 \
--nhid_lang 128 \
--nhid_sel 256 \
--nhid_strat 128 \
--sel_weight 0.5 \
--model_file sv_model.th
dataset data/negotiate/train.txt, total 687919, unks 8718, ratio 1.27%
dataset data/negotiate/val.txt, total 74653, unks 914, ratio 1.22%
dataset data/negotiate/test.txt, total 70262, unks 847, ratio 1.21%
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    main()
  File "train.py", line 98, in main
    train_loss, valid_loss, select_loss = engine.train(corpus)
  File "/Users/diegosoaresub/Downloads/facebookIA/end-to-end-negotiator-master/src/engine.py", line 193, in train
    _, _, valid_select_loss = self.iter(N, epoch, lr, traindata, validdata)
  File "/Users/diegosoaresub/Downloads/facebookIA/end-to-end-negotiator-master/src/engine.py", line 161, in iter
    train_loss, train_time = self.train_pass(N, trainset)
  File "/Users/diegosoaresub/Downloads/facebookIA/end-to-end-negotiator-master/src/engine.py", line 104, in train_pass
    out, hid, tgt, sel_out, sel_tgt = Engine.forward(self.model, batch, volatile=False)
  File "/Users/diegosoaresub/Downloads/facebookIA/end-to-end-negotiator-master/src/engine.py", line 84, in forward
    sel_out = model.forward_selection(inpt, lang_h, ctx_h)
  File "/Users/diegosoaresub/Downloads/facebookIA/end-to-end-negotiator-master/src/models/dialog_model.py", line 178, in forward_selection
    h = torch.cat([attn, ctx_h], 2).squeeze(0)
  File "/Users/diegosoaresub/anaconda/lib/python3.6/site-packages/torch/autograd/variable.py", line 897, in cat
    return Concat.apply(dim, *iterable)
  File "/Users/diegosoaresub/anaconda/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 316, in forward
    ctx.input_sizes = [i.size(dim) for i in inputs]
  File "/Users/diegosoaresub/anaconda/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 316, in <listcomp>
    ctx.input_sizes = [i.size(dim) for i in inputs]
RuntimeError: invalid argument 2: dimension 2 out of range of 2D tensor at /Users/soumith/miniconda2/conda-bld/pytorch_1502000975045/work/torch/lib/TH/generic/THTensor.c:24

**Comment by denisyarats** [comment]
what is your pytorch version?

**Comment by diegosoaresub** [comment]
conda list | grep pytorch
**pytorch                   0.2.0                py36_1cu75    soumith**

**Comment by denisyarats** [comment]
Things might got broken with the pytorch update, I will take a look.

**Comment by diegosoaresub** [comment]
Thanks. What is the pytorch recommended version?

I just install pytorch using conda default script.

**Comment by denisyarats** [comment]
This code was developed using Pytorch 0.12

**Comment by diegosoaresub** [comment]
The follow link is the solution for this problem?

https://github.com/facebookresearch/end-to-end-negotiator/pull/5/files

**Comment by denisyarats** [comment]
I haven't tried it yet, feel free to try.

**Comment by denisyarats** [comment]
The issue should be fixed now.
