### ISSUE TITLE
non-empty torch.LongTensor is ambiguous

### ISSUE THREAD

**Issue by uclaRaymond** [facebookresearch/end-to-end-negotiator#9]
Hi,
When I ran the reinforce.py, I got the following error.
** Since my machine doesn't have GPU, I ran train.py and reinforce.py without --cuda.
** I also got the same error when running selfplay.py.
Thanks.

(py30) [root@localhost src]# python reinforce.py   --data data/negotiate   --bsz 16   --clip 1   --context_file data/negotiate/selfplay.txt   --eps 0.0   --gamma 0.95   --lr 0.5   --momentum 0.1   --nepoch 1   --nesterov   --ref_text data/negotiate/train.txt   --rl_clip 1   --rl_lr 0.1   --score_threshold 6   --sv_train_freq 4   --temperature 0.5   --alice_model sv_model.th   --bob_model sv_model.th   --output_model_file rl_model.th
Traceback (most recent call last):
  File "reinforce.py", line 165, in <module>
    main()
  File "reinforce.py", line 159, in main
    reinforce.run()
  File "reinforce.py", line 57, in run
    self.dialog.run(ctxs, self.logger)
  File "/root/end-to-end-negotiator-master/src/dialog.py", line 170, in run
    out = writer.write()
  File "/root/end-to-end-negotiator-master/src/agent.py", line 329, in write
    100, self.args.temperature)
  File "/root/end-to-end-negotiator-master/src/models/dialog_model.py", line 282, in write
    if inpt:
  File "/root/anaconda3/envs/py30/lib/python3.6/site-packages/torch/autograd/variable.py", line 123, in __bool__
    torch.typename(self.data) + " is ambiguous")
RuntimeError: bool value of Variable objects containing non-empty torch.LongTensor is ambiguous

**Comment by denisyarats** [comment]
Hey, I just pushed a fix for this: https://github.com/facebookresearch/end-to-end-negotiator/commit/9a39ade348949a7b0b1bb1605fd901e97e0efca5

Let me know if it helps.

**Comment by uclaRaymond** [comment]
It fixes it. Thanks.
